# Generated by Django 4.2.20 on 2025-03-18 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=300, verbose_name='Nombre')),
                ('phone', models.CharField(blank=True, max_length=15, verbose_name='Telefono')),
                ('age', models.IntegerField(blank=True, verbose_name='Edgad')),
            ],
        ),
    ]
